### PR TITLE
setup_pkg(): fix check for pkgname-32bit + update gcc-multilib

### LINKED ISSUE #2334: xbps-src: No longer able to create gcc-multilib
I think something is wrong with the current state of xbps-src, unless I'm missing the point.
```
jbu@mybox:~/src/void-packages$ ./xbps-src pkg gcc-multilib
[*] Updating `http://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
x86_64-repodata: 9.8KB [avg rate: 13MB/s]
[*] Updating `http://muslrepo.voidlinux.eu/current/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `http://muslrepo.voidlinux.eu/current/x86_64-repodata': Not Found
[*] Updating `http://muslrepo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
ERROR: [reposync] failed to fetch file `http://muslrepo.voidlinux.eu/current/nonfree/x86_64-repodata': Not Found
[*] Updating `http://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
x86_64-repodata: 334KB [avg rate: 454MB/s]
[*] Updating `http://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
x86_64-repodata: 6841B [avg rate: 6755KB/s]
=> gcc-multilib-4.9.2_1: removing autodeps, please wait...
=> ERROR: xbps-src: unexistent file: /void-packages/srcpkgs/glibc-32bit/template
=> ERROR: gcc-multilib-4.9.2_1: failed to transform dependency glibc-32bit
```
I believe it worked some time ago. What is wrong?
Is it just that gcc is at 4.9.3 and no longer 4.9.2?

### PR DESCRIPTION
**Pull request by pullmoll**
Trying to build `gcc-multilib` failed because `glibc-32bit`
has no separate `srcpkg/glibc-32bit/template`, but is a
result of building `glibc` for target arch `i686`.

+ Also update gcc-multilib to gcc-4.9.3

### CODE REVIEW

**Comment by pullmoll** [comment]
It doesn't work right yet: gcc-multilib fails.
I'll try to get the fix done right.

File: common/xbps-src/shutils/common.sh [hunk 1]
```diff
@@ -215,6 +215,7 @@ setup_pkg() {
     local val _vars f dbgflags arch
 
     [ -z "$pkg" ] && return 1
+    basepkg=${pkg%-32bit}
```
Comment (xtraeme) [inline common/xbps-src/shutils/common.sh]: Seems to be reasonable; please make `basepkg` a local var.
